# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MuseoDeTodos' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MuseoDeTodos

  target 'MuseoDeTodosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MuseoDeTodosUITests' do
    # Pods for testing
  end
  
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'RealmSwift', '~>10'
  
end
